default: &default
  adapter: postgresql
  encoding: unicode
  database: project_development
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: project_development
  pool: 5
  timeout: 5000

test:
  <<: *default
  database: project_test
  pool: 5
  timeout: 5000

production:
  <<: *default
  database: project_production
  username: username
  password: <%= ENV['PROJECT_DATABASE_PASSWORD'] %>
  pool: 5
  timeout: 5000